const players = [
    {
        firstKey : true,
        lKey : "",
        rKey : "",
        x : Math.random()*960 + 20,
        y : Math.random()*960 + 20,
        speed : 1,
        breakInt : Math.random()*750,
        breakCount : 0,
        inBreak : false,
        l : Math.random()*2,
        color : "red",
        width : 3,
        right : false,
        left : false,
        chosed : false,
        alive : true,
        point : 0,
        boosts : [],
        square : false,
    },
    {
        firstKey : true,
        lKey : "",
        rKey : "",
        x : Math.random()*960 + 20,
        y : Math.random()*960 + 20,
        speed : 1,
        breakInt : Math.random()*750,
        breakCount : 0,
        inBreak : false,
        l : Math.random()*2,
        color : "green",
        width : 3,
        right : false,
        left : false,
        chosed : false,
        alive : true,
        point : 0,
        boosts : [],
        square : false,
    },
    {
        firstKey : true,
        lKey : "",
        rKey : "",
        x : Math.random()*960 + 20,
        y : Math.random()*960 + 20,
        speed : 1,
        breakInt : Math.random()*750,
        breakCount : 0,
        inBreak : false,
        l : Math.random()*2,
        color : "purple",
        width : 3,
        right : false,
        left : false,
        chosed : false,
        alive : true,
        point : 0,
        boosts : [],
        square : false,
    },
    {
        firstKey : true,
        lKey : "",
        rKey : "",
        x : Math.random()*960 + 20,
        y : Math.random()*960 + 20,
        speed : 1,
        breakInt : Math.random()*750,
        breakCount : 0,
        inBreak : false,
        l : Math.random()*2,
        color : "teal",
        width : 3,
        right : false,
        left : false,
        chosed : false,
        alive : true,
        point : 0,
        boosts : [],
        square : false,
    },
    {
        firstKey : true,
        lKey : "",
        rKey : "",
        x : Math.random()*960 + 20,
        y : Math.random()*960 + 20,
        speed : 1,
        breakInt : Math.random()*750,
        breakCount : 0,
        inBreak : false,
        l : Math.random()*2,
        color : "orange",
        width : 3,
        right : false,
        left : false,
        chosed : false,
        alive : true,
        point : 0,
        boosts : [],
        square : false,
    },
    {
        firstKey : true,
        lKey : "",
        rKey : "",
        x : Math.random()*960 + 20,
        y : Math.random()*960 + 20,
        speed : 1,
        breakInt : Math.random()*750,
        breakCount : 0,
        inBreak : false,
        l : Math.random()*2,
        color : "grey",
        width : 3,
        right : false,
        left : false,
        chosed : false,
        alive : true,
        point : 0,
        boosts : [],
        square : false,
    },
]